name: Code Review

on: [pull_request]

jobs:

  # -- ESLINT -----------------------------------------------------------------
  eslint:
    name: Code Review / ESLint
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # tag=v3.0.1

      - name: Run ESLint
        uses: reviewdog/action-eslint@48a0377239b23534996517492127d850dd9b7642 # tag=v1.16.0
