name: Code Review

on: [pull_request]

jobs:

  # -- DOCKER -----------------------------------------------------------------
  hadolint:
    name: runner / hadolint
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0

      - name: Run ESLint
        uses: reviewdog/action-eslint@48a0377239b23534996517492127d850dd9b7642 # tag=v1.16.0
